POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Harry Potter and the prisoner of Azkaban",
  "author": "J.K. Rowling",
  "url": "https://en.wikipedia.org/wiki/Harry_Potter_and_the_Prisoner_of_Azkaban",
  "likes": 500034000
}